// swift-tools-version: 5.10
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "SFSymbolKit",
    platforms: [
        .iOS(.v15),
        .macOS(.v14)
    ],
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "SFSymbolKit",
            targets: ["SFSymbolKit"]),
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(
            name: "SFSymbolKit",
            resources: [
                .copy("Symbols"),
                .copy("Fonts/SFSymbolsFallback.otf"),
                .copy("Fonts/SF-Pro.ttf"),
                .copy("Fonts/SF-Pro-Text-UltralightItalic.otf"),
                .copy("Fonts/SF-Pro-Text-Ultralight.otf"),
                .copy("Fonts/SF-Pro-Text-ThinItalic.otf"),
                .copy("Fonts/SF-Pro-Text-Thin.otf"),
                .copy("Fonts/SF-Pro-Text-SemiboldItalic.otf"),
                .copy("Fonts/SF-Pro-Text-Semibold.otf"),
                .copy("Fonts/SF-Pro-Text-RegularItalic.otf"),
                .copy("Fonts/SF-Pro-Text-Regular.otf"),
                .copy("Fonts/SF-Pro-Text-MediumItalic.otf"),
                .copy("Fonts/SF-Pro-Text-Medium.otf"),
                .copy("Fonts/SF-Pro-Text-LightItalic.otf"),
                .copy("Fonts/SF-Pro-Text-Light.otf"),
                .copy("Fonts/SF-Pro-Text-HeavyItalic.otf"),
                .copy("Fonts/SF-Pro-Text-Heavy.otf"),
                .copy("Fonts/SF-Pro-Text-BoldItalic.otf"),
                .copy("Fonts/SF-Pro-Text-Bold.otf"),
                .copy("Fonts/SF-Pro-Text-BlackItalic.otf"),
                .copy("Fonts/SF-Pro-Text-Black.otf"),
                .copy("Fonts/SF-Pro-Rounded-Ultralight.otf"),
                .copy("Fonts/SF-Pro-Rounded-Thin.otf"),
                .copy("Fonts/SF-Pro-Rounded-Semibold.otf"),
                .copy("Fonts/SF-Pro-Rounded-Regular.otf"),
                .copy("Fonts/SF-Pro-Rounded-Medium.otf"),
                .copy("Fonts/SF-Pro-Rounded-Light.otf"),
                .copy("Fonts/SF-Pro-Rounded-Heavy.otf"),
                .copy("Fonts/SF-Pro-Rounded-Bold.otf"),
                .copy("Fonts/SF-Pro-Rounded-Black.otf"),
                .copy("Fonts/SF-Pro-Italic.ttf"),
                .copy("Fonts/SF-Pro-Display-UltralightItalic.otf"),
                .copy("Fonts/SF-Pro-Display-Ultralight.otf"),
                .copy("Fonts/SF-Pro-Display-ThinItalic.otf"),
                .copy("Fonts/SF-Pro-Display-Thin.otf"),
                .copy("Fonts/SF-Pro-Display-SemiboldItalic.otf"),
                .copy("Fonts/SF-Pro-Display-Semibold.otf"),
                .copy("Fonts/SF-Pro-Display-RegularItalic.otf"),
                .copy("Fonts/SF-Pro-Display-Regular.otf"),
                .copy("Fonts/SF-Pro-Display-MediumItalic.otf"),
                .copy("Fonts/SF-Pro-Display-Medium.otf"),
                .copy("Fonts/SF-Pro-Display-LightItalic.otf"),
                .copy("Fonts/SF-Pro-Display-Light.otf"),
                .copy("Fonts/SF-Pro-Display-HeavyItalic.otf"),
                .copy("Fonts/SF-Pro-Display-Heavy.otf"),
                .copy("Fonts/SF-Pro-Display-BoldItalic.otf"),
                .copy("Fonts/SF-Pro-Display-Bold.otf"),
                .copy("Fonts/SF-Pro-Display-BlackItalic.otf"),
                .copy("Fonts/SF-Pro-Display-Black.otf"),
                .copy("Fonts/SF-Compact.ttf"),
                .copy("Fonts/SF-Compact-Text-UltralightItalic.otf"),
                .copy("Fonts/SF-Compact-Text-Ultralight.otf"),
                .copy("Fonts/SF-Compact-Text-ThinItalic.otf"),
                .copy("Fonts/SF-Compact-Text-Thin.otf"),
                .copy("Fonts/SF-Compact-Text-SemiboldItalic.otf"),
                .copy("Fonts/SF-Compact-Text-Semibold.otf"),
                .copy("Fonts/SF-Compact-Text-RegularItalic.otf"),
                .copy("Fonts/SF-Compact-Text-Regular.otf"),
                .copy("Fonts/SF-Compact-Text-MediumItalic.otf"),
                .copy("Fonts/SF-Compact-Text-Medium.otf"),
                .copy("Fonts/SF-Compact-Text-LightItalic.otf"),
                .copy("Fonts/SF-Compact-Text-Light.otf"),
                .copy("Fonts/SF-Compact-Text-HeavyItalic.otf"),
                .copy("Fonts/SF-Compact-Text-Heavy.otf"),
                .copy("Fonts/SF-Compact-Text-BoldItalic.otf"),
                .copy("Fonts/SF-Compact-Text-Bold.otf"),
                .copy("Fonts/SF-Compact-Text-BlackItalic.otf"),
                .copy("Fonts/SF-Compact-Text-Black.otf"),
                .copy("Fonts/SF-Compact-Rounded-Ultralight.otf"),
                .copy("Fonts/SF-Compact-Rounded-Thin.otf"),
                .copy("Fonts/SF-Compact-Rounded-Semibold.otf"),
                .copy("Fonts/SF-Compact-Rounded-Regular.otf"),
                .copy("Fonts/SF-Compact-Rounded-Medium.otf"),
                .copy("Fonts/SF-Compact-Rounded-Light.otf"),
                .copy("Fonts/SF-Compact-Rounded-Heavy.otf"),
                .copy("Fonts/SF-Compact-Rounded-Bold.otf"),
                .copy("Fonts/SF-Compact-Rounded-Black.otf"),
                .copy("Fonts/SF-Compact-Italic.ttf"),
                .copy("Fonts/SF-Compact-Display-Ultralight.otf"),
                .copy("Fonts/SF-Compact-Display-Thin.otf"),
                .copy("Fonts/SF-Compact-Display-Semibold.otf"),
                .copy("Fonts/SF-Compact-Display-Regular.otf"),
                .copy("Fonts/SF-Compact-Display-Medium.otf"),
                .copy("Fonts/SF-Compact-Display-Light.otf"),
                .copy("Fonts/SF-Compact-Display-Heavy.otf"),
                .copy("Fonts/SF-Compact-Display-Bold.otf"),
                .copy("Fonts/SF-Compact-Display-Black.otf")
            ]),
        .testTarget(
            name: "SFSymbolKitTests",
            dependencies: ["SFSymbolKit"]),
    ]
)
